name: Demo to create automatic PR

on:
  pull_request:
    branches:
      - feature/*
  
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "Auto Pull Request"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
